server:
  name: final-chapter2
  env: local
  http:
    port: 8080
dataSource:
  mode: POSTGRE
  migrate: false
  postgres:
    master:
      Host: localhost
      Port: 5432
      DBName: final_project
      Username: postgres
      Password: 123456
      maxIdleConnection: 10
      maxOpenConnection: 10
      maxIdleTime: 10